---

- name: add route to the network
  shell: |
    ip route add 192.168.70.0/24 dev eth1

- name: set net.ipv4.ip_forward=1
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes


- name: Flush all chain in iptable
  iptables:
    flush: yes
#sudo iptables -F

- name: Flush all chain in table Nat
  iptables:
    table: nat
#sudo iptables -t nat -F

- name: Setup nat POSTROUTING
  iptables:
    table: nat
    chain: POSTROUTING
    to_source: 10.0.2.15
    destination: "! 192.168.70.0/24"
    out_interface: eth0
    jump: SNAT
  become: yes

#sudo iptables -t nat -A POSTROUTING ! -d 192.168.70.0/24 -o eth0 -j SNAT --to-source 10.0.2.15



