---

- name: add route to the network
  shell: |
    ip route add {{ gateway_setup["internal_network"] }}/{{ gateway_setup["mask"] }} dev {{ gateway_setup["local_network_if"] }}
  ignore_errors: true

- name: set net.ipv4.ip_forward=1
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes


- name: Flush all chain in table Nat
  iptables:
    flush:
    table: nat
  ignore_errors: true
#sudo iptables -t nat -F

- name: Setup nat POSTROUTING
  iptables:
    table: nat
    chain: POSTROUTING
    to_source: "{{ gateway_setup['ip_source'] }}"
    destination: "! {{ gateway_setup['destination'] }}"
    out_interface: "{{ gateway_setup['out_interface'] }}""
    jump: SNAT

#sudo iptables -t nat -A POSTROUTING ! -d 192.168.70.0/24 -o eth0 -j SNAT --to-source 10.0.2.15



