apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: default
subsets:
- addresses:
  - ip: 192.168.254.14
    nodeName: k8s-worker01.cluster.local
    targetRef:
      kind: Pod
      name: grafana-587996867-qlnvk
      namespace: default
  ports:
  - name: service
    port: 3000
    protocol: TCP
