apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: default
rules:
- apiGroups:
  - extensions
  resourceNames:
  - grafana
  resources:
  - podsecuritypolicies
  verbs:
  - use
