apiVersion: v1
data:
  admin-password: Uk53WllXWVlPSURhZmRkNGNOMW82Yml3MG0yOFBudUNudUJ2WWtFNQ==
  admin-user: YWRtaW4=
  ldap-toml: ""
kind: Secret
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: default
type: Opaque
