apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: default
spec:
  clusterIP: 10.96.35.240
  externalTrafficPolicy: Cluster
  ports:
  - name: service
    nodePort: 30033
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana
    release: grafana
  sessionAffinity: None
  type: NodePort
