---

- hosts: ntpservers
  become: yes
  roles:
    - setup_nfsserver

- hosts: all,!nfsservers
  become: yes
  roles:
    - prepare-server
    - cri-o
    - init_k8s
    - join_k8s
    - add_worker
    - add_master
    - install_tools
    - deploy_monitoring
    - add_pv_pvc

