---

- debug:
    var: remove_nodes
  run_once: true

- debug:
    var: add_nodes
  run_once: true

- name: Drain node(s), ignore daemonsets and delete local data
  shell: |
    kubectl drain {{ hostvars[item].ansible_facts.nodename }} --ignore-daemonsets --delete-local-data {{ options|default('') }}
  delegate_to: "{{ initiator }}"
  ignore_errors: true
  with_items:
    - "{{ target }}"


- name: Remove node(s)
  shell:
    kubectl delete node {{ hostvars[item].ansible_facts.nodename }} {{ options|default('') }}
  delegate_to: "{{ initiator }}"
  ignore_errors: true
  with_items:
    - "{{ target }}"

- name: Remove node(s)
  shell:
    kubeadm reset --force
  when: inventory_hostname in target
