apiVersion: v1
data:
  alertmanager.yml: |
    global: {}
    receivers:
    - name: default-receiver
    route:
      group_interval: 5m
      group_wait: 10s
      receiver: default-receiver
      repeat_interval: 3h
kind: ConfigMap
metadata:
  creationTimestamp: "2019-12-21T20:57:56Z"
  labels:
    app: prometheus
    chart: prometheus-9.7.0
    component: alertmanager
    heritage: Helm
    release: prometheus
  name: prometheus-alertmanager
  namespace: default
  resourceVersion: "44091"
  selfLink: /api/v1/namespaces/default/configmaps/prometheus-alertmanager
  uid: d5a0ef8c-4eaa-434d-9163-97c8991a5e95
