apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2019-12-21T20:57:58Z"
  creationTimestamp: "2019-12-21T20:57:58Z"
  labels:
    app: prometheus
    chart: prometheus-9.7.0
    component: alertmanager
    heritage: Helm
    release: prometheus
  name: prometheus-alertmanager
  namespace: default
  resourceVersion: "44134"
  selfLink: /api/v1/namespaces/default/endpoints/prometheus-alertmanager
  uid: cca2e15a-8e9d-4bbd-b839-1c4826e60982
