apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: "2019-12-21T20:57:57Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: prometheus
    chart: prometheus-9.7.0
    component: alertmanager
    heritage: Helm
    release: prometheus
  name: prometheus-alertmanager
  namespace: default
  resourceVersion: "44095"
  selfLink: /api/v1/namespaces/default/persistentvolumeclaims/prometheus-alertmanager
  uid: e7b78700-bbbc-4820-b998-905753935d3f
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
status:
  phase: Pending
