apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-12-21T20:57:58Z"
  labels:
    app: prometheus
    chart: prometheus-9.7.0
    component: alertmanager
    heritage: Helm
    release: prometheus
  name: prometheus-alertmanager
  namespace: default
  resourceVersion: "44133"
  selfLink: /api/v1/namespaces/default/services/prometheus-alertmanager
  uid: 70807b3e-4040-45fc-9549-86ceaf402835
spec:
  clusterIP: 10.96.109.255
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9093
  selector:
    app: prometheus
    component: alertmanager
    release: prometheus
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
