---

- name: (LOCAL) Create Persistent Volume definition
  template:
    src: local_pv.yml.j2
    dest: /var/tmp/local_pv_create.yaml
    backup: yes

- name: (LOCAL) Create Persistent Volume Claim definition
  template:
    src: local_pvc.yml.j2
    dest: /var/tmp/local_pvc_create.yaml
    backup: yes

