---

#
#
# these CRI-O repositories are not longer available
#
#- name: Add CRI-O repositories for version 1.11 1.13 1.14 and 1.15
#  yum_repository:
#    name: "{{ item.name }}"
#    file: crio
#    description: "{{ item.description }}"
#    baseurl: "{{ item.baseurl }}" 
#    enabled: yes
#    gpgcheck: no
#  with_items:
#    - name: CRI-O-115
#      description: CRI-O-115
#      baseurl: https://cbs.centos.org/repos/paas7-crio-115-candidate/x86_64/os/
#    - name: CRI-O-111
#      description: CRI-O-111
#      baseurl: https://cbs.centos.org/repos/paas7-crio-311-candidate/x86_64/os/
#    - name: CRI-O-114
#      description: CRI-O-114
#      baseurl: https://cbs.centos.org/repos/paas7-crio-114-candidate/x86_64/os/
#    - name: CRI-O-113
#      description: CRI-O-113
#      baseurl: https://cbs.centos.org/repos/paas7-crio-113-candidate/x86_64/os
#
#- name: Update cache
#  yum:
#    update_cache: yes

#- name: Add Centos-extras-x86_64 repository used for containernetworking-plugins
#  yum_repository:
    #name: Centos-extras-x86_64
    #file: Centos-extras-x86_64
    #state: absent


- block:
    - name: Add Go package for the build
      yum:
        name: "{{ go_build_required_package }}"
        state: present

    - name: Git clone of the repository containernetworking
      git:
        repo: "{{ cni_git_url }}"
        dest: "{{ cni_build_temp_folder }}"
        version: "{{ cni_git_version }}"

      # build and move cni binaries
    - name: Build cni and move bin
      shell: "{{ item }}"
      loop:
        - "{{ cni_build_temp_folder }}/build_linux.sh"
        - "cp {{ cni_build_temp_folder }}/bin/* /usr/libexec/cni/"
      
      # Delete directory
    - name: Delete temporary directory
      file:
        path: "{{ cni_build_temp_folder }}"
        state: absent
  when: build_cni_from_source == true

- name: Copy rpm packages to /var/tmp
  copy:
    src: "packages/{{ item }}"
    dest: "/var/tmp/{{ item }}"
  loop:
    - containernetworking-plugins-0.7.5-1.el7.x86_64.rpm
    - cri-o-1.15.3-1.el7.x86_64.rpm
    - cri-tools-1.13.0-1.rhaos4.1.gitc06001f.el7.x86_64.rpm

- name: Install rpm containernetworking-plugins v0.7.5
  yum:
    name: /var/tmp/containernetworking-plugins-0.7.5-1.el7.x86_64.rpm
    state: present
  when: build_cni_from_source == false

- name: install CRI-O
  yum:
    name:
      - /var/tmp/cri-o-1.15.3-1.el7.x86_64.rpm
      - /var/tmp/cri-tools-1.13.0-1.rhaos4.1.gitc06001f.el7.x86_64.rpm
    state: present

- name: Create crio directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ crio.root }}"
    - "{{ crio.runroot }}"
    - "{{ crio.config_directory }}"
    - "{{ crio.log_dir }}"
    - "/usr/share/containers/oci/hooks.d"

- block:
    - name: (FLANNEL) Push CNI config for CRI-O
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - src: 10-crio-flannel.conf.j2
          dest: "{{ cni_crio_config_directory }}/10-crio-flannel.conf"
        #- src: 99-loopback.conf.j2
        #  dest: "{{ cni_crio_config_directory }}/99-loopback.conf"
  when: pod_network == "flannel"

- name: Push CRI-O configuration
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: crio.conf.j2
      dest: /etc/crio/crio.conf

- name: systemd daemon reload
  systemd:
    daemon_reload: yes

- name: start cri-o
  systemd:
    name: crio
    state: restarted
    enabled: yes

    #will be managed by handlers
    #- name: Start services
    #  systemd:
    #    enabled: yes
    #    state: started
    #    name: "{{ item }}"
    #  with_items:
    #    - crio
    
