---

- name: Generate kubernetes config file for grafana and prometheus
  template:
    src: "{{ item }}.j2"
    dest: "/var/tmp/{{ item }}"
  ignore_errors: yes
  with_items:
    - clusterRole.yaml
    - grafana_config-map.yaml
    - grafana_namespace.yaml
    - grafana_secret.yaml
    - grafana_service-account.yaml
    - grafana_service.yaml
    - grafana_statefulset.yaml
    - node-exporter-daemonset.yaml
    - prom_config-map.yaml
    - prometheus-deployment.yaml
    - prometheus_namespace.yaml
  when: hostvars[inventory_hostname]['cluster_initiator'] == "true"