---

- name: Deploy monitoring using HELM
  include: monitoring_helm_deploy.yml
  ignore_errors: yes
  when: 
    - hostvars[inventory_hostname]['cluster_initiator'] == "true"
    - deploy_monitoring_using_helm|default(false) == true

- name: Deploy advanced Monitoring
  include: monitoring_advanced_deploy.yml
  ignore_errors: yes
  when:
    - hostvars[inventory_hostname]['cluster_initiator'] == "true"
    - deploy_monitoring_using_helm|default(false) == false

