---

- name: Install podman
  yum:
    name: podman
    disable_excludes: all
    update_cache: yes
    state: latest
  when: podman.install == true


- name: Install buildah
  yum:
    name: buildah
    disable_excludes: all
    update_cache: yes
    state: latest
  when: podman.install == true


- name: Install skopeo
  yum:
    name: skopeo
    disable_excludes: all
    update_cache: yes
    state: latest
  when: skopeo.install == true


- name: Install Helm
  block:
    - name: Download and unarchive Helm
      unarchive:
        src: "{{ helm.url }}"
        dest: /var/tmp
        remote_src: yes

    - name: "Put the binary file in {{ helm.bin_directory }}"
      copy:
        src: /var/tmp/linux-amd64/helm
        dest: "{{ helm.bin_directory }}/helm"
        mode: a+x 
        remote_src: yes

    - name: Add helm repos
      shell: |
        {{ helm.bin_directory }}/helm repo add {{ item.name }} {{ item.url }}
      ignore_errors: true
      with_items: "{{ helm.repos }}"
      when: helm.add_repos == true

    - name: Update repos
      shell: |
        {{ helm.bin_directory }}/helm repo update
      ignore_errors: true
      when: helm.update_repos == true

  when: helm.install == true

  #Helm
  #  helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com/
  #  helm repo add brigade https://brigadecore.github.io/charts
  #  helm repo add bitnami https://charts.bitnami.com/bitnami

  #  /usr/local/bin/helm repo update

  #  https://github.com/helm/charts/tree/master/stable
