---

- name: Unlink network interfaces
  shell:
    for if in $(ip -br a s | egrep -v "lo|ens" | awk '{print $1}'); do
      ip link delete $if
    done
  ignore_errors: yes

- name: Remove file from /etc/cni/net.d and /etc/crio/net.d
  shell: |
    rm -rf /etc/cni/net.d/*
    rm -rf /etc/crio/net.d/*
  ignore_errors: yes

- name: Uninstall CRI-O packages
  yum:
    name:
      - cri-tools 
      - cri-o 

# cri-tools-1.13.0-1.rhaos4.1.gitc06001f.el7.x86_64
# cri-o-1.15.2-1.el7.x86_64

- name: Uninstall kubernetes packages
  yum:
    name:
      - kubeadm
      - kubectl
      - kubelet
      - kubernetes-cni
    state: absent

# kubelet-1.18.2-0.x86_64
# kubeadm-1.18.2-0.x86_64
# kubernetes-cni-0.7.5-0.x86_64
# kubectl-1.18.2-0.x86_64
        
        

         
         
        