---

- name: Destroy k8s cluster
  shell: |
    kubeadm reset --force
  register: reset_k8s

- name: Remove images when cluster was destroyed
  shell: |
    crictl rmi $(crictl images -q)
  ignore_errors: true
  when: remove_images_when_cluster_is_destroyed == true

- name: Stop CRIO
  systemd:
    name: crio
    state: stopped

- name: Unlink network interfaces
  shell:
    for if in $(ip -br a s | egrep -v "lo|ens" | awk '{print $1}'); do
      ip link delete $if
    done
  ignore_errors: yes

- name: Remove file from /etc/cni/net.d and /etc/crio/net.d
  shell: |
    rm -rf /etc/cni/net.d/*
    rm -rf /etc/crio/net.d/*
  ignore_errors: yes

- block:
    - name: Reboot servers
      reboot:
        msg: "Kubernetes cluster was destroyed now we go to reboot that servers."

    - name: waiting the servers to become reachable
      wait_for_connection:
        connect_timeout: 20
        delay: 5
  when: reboot_servers_when_cluster_is_destroyed == true 
 
