apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/probe: pushgateway
  creationTimestamp: "2019-12-21T20:57:58Z"
  labels:
    app: prometheus
    chart: prometheus-9.7.0
    component: pushgateway
    heritage: Helm
    release: prometheus
  name: prometheus-pushgateway
  namespace: default
  resourceVersion: "44130"
  selfLink: /api/v1/namespaces/default/services/prometheus-pushgateway
  uid: cb513283-9535-4856-89cd-d5695adbadb1
spec:
  clusterIP: 10.96.71.136
  ports:
  - name: http
    port: 9091
    protocol: TCP
    targetPort: 9091
  selector:
    app: prometheus
    component: pushgateway
    release: prometheus
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
