apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2019-12-21T20:57:57Z"
  labels:
    app: prometheus
    chart: prometheus-9.7.0
    component: pushgateway
    heritage: Helm
    release: prometheus
  name: prometheus-pushgateway
  namespace: default
  resourceVersion: "44125"
  selfLink: /api/v1/namespaces/default/serviceaccounts/prometheus-pushgateway
  uid: b6660e2c-7a09-4717-8ccb-4031ede18565
secrets:
- name: prometheus-pushgateway-token-xmjsr
