apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2019-12-21T20:57:57Z"
  labels:
    app: prometheus
    chart: prometheus-9.7.0
    component: kube-state-metrics
    heritage: Helm
    release: prometheus
  name: prometheus-kube-state-metrics
  namespace: default
  resourceVersion: "44119"
  selfLink: /api/v1/namespaces/default/serviceaccounts/prometheus-kube-state-metrics
  uid: ec870a88-d1f5-4ffa-8f38-f168ad4982e1
secrets:
- name: prometheus-kube-state-metrics-token-9ncgp
