apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: "2019-12-21T20:57:57Z"
  labels:
    app: prometheus
    chart: prometheus-9.7.0
    component: server
    heritage: Helm
    release: prometheus
  name: prometheus-server
  resourceVersion: "44103"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/prometheus-server
  uid: 8173cb82-49b8-4d68-8bd3-ee53ac12c6f9
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/proxy
  - nodes/metrics
  - services
  - endpoints
  - pods
  - ingresses
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - ingresses/status
  - ingresses
  verbs:
  - get
  - list
  - watch
- nonResourceURLs:
  - /metrics
  verbs:
  - get
