apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: "2019-12-21T20:57:57Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: prometheus
    chart: prometheus-9.7.0
    component: server
    heritage: Helm
    release: prometheus
  name: prometheus-server
  namespace: default
  resourceVersion: "44094"
  selfLink: /api/v1/namespaces/default/persistentvolumeclaims/prometheus-server
  uid: 1ba66db1-e550-4bc2-82e2-cb8ef7fa80c6
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeMode: Filesystem
status:
  phase: Pending
