apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2019-12-21T20:57:57Z"
  labels:
    app: prometheus
    chart: prometheus-9.7.0
    component: server
    heritage: Helm
    release: prometheus
  name: prometheus-server
  namespace: default
  resourceVersion: "44109"
  selfLink: /api/v1/namespaces/default/serviceaccounts/prometheus-server
  uid: 9b9a5d1b-6d8e-43b7-8a52-983d2372278d
secrets:
- name: prometheus-server-token-84r4x
